name: Deploy2

on:
  workflow_call:
    inputs:
      projects:
        description: A JSON array of projects to deploy
        type: string
        required: true
      environment:
        description: The name of the environment to deploy to
        type: string
        required: true
      version:
        description: The image version to deploy
        type: string
        required: true

  workflow_dispatch:
    inputs:
      projects:
        description: Project
        type: choice
        required: true
        options:
          - '["mercury-data-transform-load"]'
          # ^ add new projects here
          # GitHub Actions doesn't support dynamic choices, we must add each project here to enable manual deployments
          # See https://github.com/community/community/discussions/11795
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - test
          - preprod
          - prod
      version:
        description: Image version
        type: string
        required: true
      part:
        description: Frontend or Backend
        type: choice
        required: true
        options:
          - BACKEND
          - FRONTEND


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          project: ${{ fromJson(inputs.projects) }}
    concurrency: deploy-${{ matrix.project }}-${{ inputs.environment }}
    environment:
      name: ${{ inputs.environment }}
    steps:
        - name: Check if backend
          if: startswith(inputs.part, 'BACKEND')
          run: echo "MY_SECRET=${{ vars.BACKEND_SECRET }}""
        - name: Check if frontend
          if: startswith(inputs.part, 'FRONTEND')
          run: echo "MY_SECRET=${{ vars.FRONTEND_SECRET }}"          
        - name: Bash Test Step
          shell: bash
          run: |
            echo "inputs.env ${{ inputs.environment }}"
            echo "inputs.project ${{ matrix.project }}"
            echo "inputs.version ${{ inputs.version }}"
            echo "part access key $MY_SECRET"