name: Parent security workflow

on:
  workflow_dispatch:
    inputs:
      job:
        description: Security job to run
        type: choice
        required: true
        options:
          - owasp
          - trivy
          - veracode
  schedule:
    - cron: "30 5 * * MON" # Every Monday at 05:30 UTC

jobs:
  security-owasp-extractor-check:
    if: inputs.job == 'owasp'
    name: Legacy Data Extractor OWASP dependency check
    uses: ./.github/workflows/security_owasp.yml
    with:
      subproject: mercury-data-extractor
  security-owasp-transformer-check:
    if: inputs.job == 'owasp'
    name: Legacy Transformer security OWASP dependency check
    uses: ./.github/workflows/security_owasp.yml
    with:
      subproject: mercury-data-transform-load
  security-owasp-test-gen-check:
    if: inputs.job == 'owasp'
    name: Legacy Test Data Generator security OWASP dependency check
    uses: ./.github/workflows/security_owasp.yml
    with:
      subproject: mercury-test-generator
  # security-trivy-transformer-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Legacy Transformer trivy scan
  #       if: inputs.job == 'trivy'
  #       uses: ./.github/workflows/security_trivy.yml
  #       with:
  #         subproject: mercury-data-transform-load

  security-trivy-transformer-check:
    name: Legacy Transformer trivy scan
    uses: ./.github/workflows/security_trivy.yml
    with:
      subproject: mercury-data-transform-load