name: Security workflow

on:
  workflow_call:
    inputs:
      subproject:
        required: true
        type: string

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     project: ${{ inputs.subproject }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Transform ECR path
        if: inputs.subproject == 'mercury-data-transform-load'
        shell: bash
        run: |
          ecr=amazon.ecr.transform:latest
          echo "ECR=$ecr" >> $GITHUB_ENV
          echo "ecr=$ecr" | tee -a $GITHUB_OUTPUT

      - name: Run trivy scan on transform
        if: inputs.subproject == 'mercury-data-transform-load'
        shell: bash
        run: |
          echo "running trivy scan on ${{ inputs.subproject}}"
          echo "ecr=$ECR"

